demo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'demo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),

    # Doorsale urls containing urls for all apps
    url(r'^', include('doorsale.urls')),
]

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doorsale/conf/project_template/project_name/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    # Doorsale urls containing urls for all apps
    url(r'^', include('doorsale.urls')),
)

# In Debug mode we need to serve media files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doorsale/sales/urls.py
from django.conf.urls import url

from doorsale.sales.views import add_to_cart, remove_from_cart, remove_all_from_cart
from doorsale.sales.views import CheckoutCartView, CheckoutBillingView, CheckoutShippingView, \
    CheckoutPaymentView, CheckoutOrderView, CheckoutReceiptView, PrintReceiptView

urlpatterns = [
    url(r'^cart/add/$', add_to_cart, name='sales_add_to_cart'),
    url(r'^cart/remove/$', remove_from_cart, name='sales_remove_from_cart'),
    url(r'^cart/remove/all$', remove_all_from_cart, name='sales_remove_all_from_cart'),
    url(r'^checkout/cart/$', CheckoutCartView.as_view(), name='sales_checkout_cart'),
    url(r'^checkout/billing/$', CheckoutBillingView.as_view(), name='sales_checkout_billing'),
    url(r'^checkout/shipping/$', CheckoutShippingView.as_view(), name='sales_checkout_shipping'),
    url(r'^checkout/payment/$', CheckoutPaymentView.as_view(), name='sales_checkout_payment'),
    url(r'^checkout/order/$', CheckoutOrderView.as_view(), name='sales_checkout_order'),
    url(r'^checkout/receipt/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        CheckoutReceiptView.as_view(), name='sales_checkout_receipt'),
    url(r'^checkout/receipt/print/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        PrintReceiptView.as_view(), name='sales_print_receipt'),
]

doorsale/urls.py
from django.conf.urls import include, url


# Doorsale apps urls
urlpatterns = [
    url(r'^', include('doorsale.catalog.urls')),
    url(r'^accounts/', include('doorsale.accounts.urls')),
    url(r'^sales/', include('doorsale.sales.urls')),
    url(r'^payments/', include('doorsale.payments.urls')),
    url(r'^pages/', include('doorsale.pages.urls'))
]

doorsale/geo/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Country(models.Model):
    """
    Represents a country
    """
    name = models.CharField(max_length=100, unique=True)
    allow_billing = models.BooleanField(default=True, help_text='Allow billing from this country')
    allow_shipping = models.BooleanField(default=True, help_text='Allow shipping to this country')
    iso_code2 = models.CharField(max_length=2, unique=True, help_text='Two letter ISO code')
    iso_code3 = models.CharField(max_length=3, unique=True, help_text='Three letter ISO code')
    iso_numeric = models.IntegerField(help_text='Numeric ISO code')
    subject_to_vat = models.BooleanField(default=False, help_text='Is VAT applicable')
    display_order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('display_order', 'name',)
        verbose_name_plural = 'Countries'

    def __unicode__(self):
        return self.name


class State(models.Model):

    """
    Represents a state
    """
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=10, help_text='Abbrevation')
    country = models.ForeignKey(Country)
    is_active = models.BooleanField(default=True)
    display_order = models.IntegerField(default=0)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('display_order', 'name',)

    def __unicode__(self):
        return self.name


class Address(models.Model):
    """
    Represents a address for billing and shipping
    """
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    company = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(Country, verbose_name='your text')
    state = models.ForeignKey(State, null=True, blank=True)
    city = models.CharField(max_length=100)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    zip_or_postal_code = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    fax_number = models.CharField(max_length=20, null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __unicode__(self):
        address = '%s %s %s' % (self.first_name, self.last_name, self.address1)

        if self.address2:
            address += ' ' + self.address2

        address += ', ' + self.city

        if self.state:
            address += ', ' + unicode(self.state)

        if self.country:
            address += ', ' + unicode(self.country)

        return address

    def get_name(self):
        return '%s %s' % (self.first_name, self.last_name)

doorsale/sales/views.py
from django.db import transaction
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.http.response import Http404
from django.core.urlresolvers import reverse
from django.template import Context
from django.template.loader import get_template
from django.shortcuts import render, get_object_or_404

from doorsale.geo.models import Address
from doorsale.sales.models import Cart, Order, PaymentMethod
from doorsale.sales.forms import AddressForm
from doorsale.catalog.views import CatalogBaseView, get_default_currency
from doorsale.exceptions import DoorsaleError
from doorsale.views import BaseView
from doorsale.utils.helpers import send_mail


@transaction.atomic
def add_to_cart(request):
    """
    Add product to cart
    """
    product_id = int(request.POST['product_id'])

    # Checking if user already has cart in session
    # otherwise create a new cart for the user
    if 'cart_id' in request.session:
        cart_id = int(request.session['cart_id'])
        cart = Cart.get_cart(cart_id)
    else:
        cart = Cart.get_cart()
        request.session['cart_id'] = cart.id

    try:
        quantity = int(request.POST['quantity'])
        if quantity > 0:
            cart.add_item(product_id, quantity, request.user)
        else:
            raise ValueError()
    except ValueError:
        return HttpResponseBadRequest('Product quantity is not correct, please enter one or more products in numbers.')

    if request.is_ajax():
        default_currency = get_default_currency(request)
        return render(request, 'sales/cart_basket.html', {'cart': cart, 'default_currency': default_currency})

    return HttpResponseRedirect(reverse('sales_checkout_cart'))


@transaction.atomic
def remove_from_cart(request):
    """
    Remove product from cart
    """
    product_id = int(request.POST['product_id'])

    # Checking if user session has cart or session may already flushed
    # Cart an empty cart for user
    if 'cart_id' in request.session:
        cart_id = int(request.session['cart_id'])
        cart = Cart.get_cart(cart_id)
        cart.remove_item(product_id)
    else:
        cart = Cart()

    if request.is_ajax():
        default_currency = get_default_currency(request)
        return render(request, 'sales/cart_basket.html', {'cart': cart, 'default_currency': default_currency})

    return HttpResponseRedirect(reverse('sales_checkout_cart'))


@transaction.atomic
def remove_all_from_cart(request):
    """
    Remove all products from cart
    """
    if request.method == 'POST':
        if 'cart_id' in request.session:
            cart_id = int(request.session['cart_id'])
            cart = Cart.get_cart(cart_id)
            cart.remove_all_items()
        else:
            cart = Cart()

        if request.is_ajax():
            default_currency = get_default_currency(request)
            return render(request, 'sales/cart_basket.html', {'cart': cart, 'default_currency': default_currency})

    return HttpResponseRedirect(reverse('sales_checkout_cart'))


class CheckoutBaseView(CatalogBaseView):
    """
    Base checkout steps view
    """
    style_name = 'sales'
    checkout_template_name = 'sales/checkout_base.html'

    def get_context_data(self, **kwargs):
        breadcrumbs = self.get_breadcrumbs()
        return super(CheckoutBaseView, self).get_context_data(
            breadcrumbs=breadcrumbs,
            step_active=self.step_active,
            steps_processed=self.steps_processed,
            checkout_template_name=self.checkout_template_name,
            **kwargs)


class CheckoutCartView(CheckoutBaseView):
    """
    Display user shopping cart
    """
    step_active = 'cart'
    steps_processed = ()
    template_name = 'sales/checkout_cart.html'

    @classmethod
    def get_breadcrumbs(cls):
        return ({'name': 'Shopping Cart', 'url': reverse('sales_checkout_cart')},)

    def get(self, request):
        if 'cart_id' in request.session:
            cart_id = int(request.session['cart_id'])
            cart = Cart.get_cart(cart_id)
        else:
            cart = Cart()

        return super(CheckoutCartView, self).get(request, cart=cart)

    def post(self, request):
        error = None
        message = None

        if 'cart_id' in request.session:
            cart_id = int(request.session['cart_id'])
            product_id = int(request.POST['product_id'])
            cart = Cart.get_cart(cart_id)
            try:
                quantity = int(request.POST['quantity'])
                if quantity > 0:
                    cart.update_item(product_id, quantity)
                    message = 'Your budget notepad has been updated.'
                else:
                    raise ValueError()
            except ValueError:
                error = 'Product quantity is not correct, please enter one or more products in numbers.'

        else:
            cart = Cart()

        return super(CheckoutCartView, self).get(request, cart=cart, error=error, message=message)


class CheckoutAddressView(CheckoutBaseView):
    """
    Base checkout view for billing and shipping address
    """
    template_name = 'sales/checkout_address.html'

    def get_context_data(self, **kwargs):
        context = super(CheckoutAddressView, self).get_context_data(**kwargs)

        addresses_filter = None
        request = self.request

        if request.user.is_authenticated():
            addresses_filter = Q(email__iexact=request.user.email) | Q(customer=request.user)

        addresses_ids = request.session.get('addresses', None)
        if addresses_ids:
            addresses_filter = (addresses_filter | Q(id__in=addresses_ids)) if addresses_filter else Q(id__in=addresses_ids)

        if addresses_filter:
            context['addresses'] = list(Address.objects.filter(addresses_filter))

        context['current_step'] = self.current_step

        return context

    def get(self, request, **kwargs):
        form = AddressForm()

        if self.session_address_key in request.session:
            del request.session[self.session_address_key]

        return super(CheckoutAddressView, self).get(request, form=form, **kwargs)

    def post(self, request):
        form = AddressForm(request.POST)
        address_id = request.POST['address_id']

        if address_id:
            address_id = int(address_id)
            address = get_object_or_404(Address, id=address_id)

            # Binding address permenantly to authenticated user
            if address.customer is None and request.user.is_authenticated():
                address.customer = request.user
                address.save()

            request.session[self.session_address_key] = address_id
            return HttpResponseRedirect(reverse(self.next_step))

        if form.is_valid():
            data = form.cleaned_data
            customer = request.user if request.user.is_authenticated() else None

            address = Address.objects.create(
                customer=customer,
                first_name=data['first_name'],
                last_name=data['last_name'],
                email=data['email'],
                address1=data['address1'],
                address2=data['address2'],
                phone_number=data['phone_number'],
                fax_number=data['fax_number'],
                zip_or_postal_code=data['zip_or_postal_code'],
                city=data['city'],
                country=data['country'],
                state=data['state'],
                company=data['company'],
                created_by=str(request.user),
                updated_by=str(request.user))

            addresses = self.request.session.get('addresses', [])
            addresses.append(address.id)
            self.request.session['addresses'] = addresses
            request.session[self.session_address_key] = address.id

            return HttpResponseRedirect(reverse(self.next_step))

        return super(CheckoutAddressView, self).get(request, form=form)


class CheckoutBillingView(CheckoutAddressView):
    """
    User billing address for order
    """
    step_active = 'billing'
    steps_processed = ['cart']
    current_step = 'sales_checkout_billing'
    next_step = 'sales_checkout_shipping'
    session_address_key = 'billing_address'

    @classmethod
    def get_breadcrumbs(cls):
        return ({'name': 'Billing Address', 'url': reverse('sales_checkout_billing')},)


class CheckoutShippingView(CheckoutAddressView):
    """
    Display user shipping address
    """
    step_active = 'shipping'
    steps_processed = ['cart', 'billing']
    current_step = 'sales_checkout_shipping'
    next_step = 'sales_checkout_payment'
    session_address_key = 'shipping_address'

    @classmethod
    def get_breadcrumbs(cls):
        return ({'name': 'Shipping Address', 'url': reverse('sales_checkout_shipping')},)


class CheckoutPaymentView(CheckoutBaseView):
    """
    Display payment method for checkout
    """
    step_active = 'payment'
    steps_processed = ['cart', 'billing', 'shipping']
    template_name = 'sales/checkout_payment.html'

    def get_context_data(self, **kwargs):
        payment_methods = PaymentMethod.get_all()
        return super(CheckoutPaymentView, self).get_context_data(payment_methods=payment_methods, **kwargs)

    @classmethod
    def get_breadcrumbs(cls):
        return ({'name': 'Payment', 'url': reverse('sales_checkout_payment')},)

    def get(self, request):
        po_number = request.session.get('po_number', None)
        payment_method = request.session.get('payment_method', None)

        return super(CheckoutPaymentView, self).get(request, payment_method=payment_method, po_number=po_number)

    def post(self, request):
        error = None
        payment_method = request.POST.get('payment_method', None)
        payment_methods = dict(PaymentMethod.ALL)

doorsale/sales/templates/sales/cart_basket.html
{% load catalog_filters %}
{% load thumbnail %}

{% with items=cart.get_items sub_total=cart.get_sub_total items_count=cart.get_items_count %}
<div class="basket">
	<div class="basket-cap">
		<div class="cart-count">
			{% if items_count %}
			<span class="basket-items-count">{{ items_count  }}</span>
			{% endif %}
            <i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
		</div>
		<span class="price">{{ sub_total|currency:default_currency }}</span>
	</div>
	<div class="basket-items" context-menu='#basket-container'>
		<span class="arrow"></span>
		{% if items %}
		<ul>
			{% for item in items %}
			{% with product=item.product %}
			<li class="cart-item">
				<div class="item-preview">
					{% thumbnail product.pics.all.0.url "54x54" as im %}
					<img src="{{ im.url }}" alt="{{ product.name }}" title="{{ product.name }}" />
					{% endthumbnail %}
				</div>
				<form method="post" class="cart-item-remove" data-ajax="true" data-ajax-url="{% url 'sales_remove_from_cart' %}" data-ajax-update="#basket-container" data-ajax-success="basketChanged();">
					{% csrf_token %}
					<input name="product_id" type="hidden" value="{{ item.product_id }}"/>
					<a onclick="javascript:$(this).closest('form').submit();" title="Remove this product."><i class="fa fa-trash-o"></i></a>
				</form>
				<a href="{{ product.get_absolute_url }}" title="{{ product.gist }}">{{ product.name }}</a>
				<p>
					<span class="price" title="Per unit price">{{ product.price|currency:default_currency }}</span>
					<br />
					<span class="quantity">Qty: {{ item.quantity }}</span>
				</p>
			</li>
			{% endwith %}
			{% endfor %}
		</ul>
		<div class="sub-total">
			<p>
				<label>Sub-Total:</label> <span class="price">{{ sub_total|currency:default_currency }}</span>
			</p>
			<a href="{% url 'sales_checkout_cart' %}" class="button"><i class="fa fa-briefcase" aria-hidden="true"></i> Contact Seller</a>
		</div>
		{% else %}
		<div class="no-items" >
			You have no items to calculate sum total on.
		</div>
		{% endif %}
	</div>
</div>
{% endwith %}

doorsale/sales/templates/sales/checkout_address.html
{% extends checkout_template_name %}

{% block checkout-content %}
<div class="action-form">
    <form method="post" action="{% url current_step %}">
        {% csrf_token %}
         <input id="address_id" name="address_id" type="hidden" value=""/>
        {% if addresses %}
        <div class="addresses">
            <h3>Existing address{{ addresses|pluralize:"es" }}</h3>
            {% for address in addresses %}
            <div class="address">
                <ul>
                    <li class="name">
                        {{ address.first_name }} {{address.last_name }}
                    </li>
                    <li>
                        {{ address.address1 }}
                    </li>
					<li>
						{{ address.zip_or_postal_code }}, {{ address.city }}, {{ address.country }}
					</li>
                    <li>
                        <label>{{ address.phone_number }}</label>
                    </li>
                    <li>
                        <label>{{ address.email }}</label>
                    </li>
                    <li>
                        <button onclick="javascript:$('#address_id').val('{{ address.id }}');">Next</button>
                    </li>
                </ul>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <h3>Add new address</h3>
        <div class="new-address">
            <div>
                <ul>
                    <li>
                        {{ form.first_name }}
                        {{ form.first_name.errors }}
                    </li>
                    <li>
                        {{ form.last_name }}
                        {{ form.last_name.errors }}
                    </li>
                    <li>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </li>
                    <li>
                        {{ form.phone_number }}
                        {{ form.phone_number.errors }}
                    </li>
                    <li>
                        {{ form.fax_number }}
                        {{ form.fax_number.errors }}
                    </li>
                    <li>
                        {{ form.company }}
                        {{ form.company.errors }}
                    </li>
                </ul>
            </div>
            <div style="float: left;">
                <ul>
                    <li>
                        {{ form.address1 }}
                        {{ form.address1.errors }}
                    </li>
                    <li>
                        {{ form.address2 }}
                        {{ form.address2.errors }}
                    </li>
                    <li>
                        {{ form.zip_or_postal_code }}
                        {{ form.zip_or_postal_code.errors }}
                    </li>
                    <li>
                        {{ form.city }}
                        {{ form.city.errors }}
                    </li>
                    <li>
                        {{ form.country }}
                        {{ form.country.errors }}
                    </li>
                    <li>
                        <select id="id_state" name="state">
                            {% for state in form.get_states %}
                            <option country="{{ state.country_id }}" value="{{ state.id }}" {% if state_id == state.id %}selected="selected"{% endif %}>{{ state.name }}</option>
                            {% endfor %}
                            <option value="">Other</option>
                        </select>
                        {{ form.state.errors }}
                    </li>
                    <li>
                        <button>Next</button>
                    </li>
                </ul>
            </div>
        </div>
    </form>    
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
    function countryChanged() {
        var country_id = $('select#id_country').val();

        $('select#id_state option').hide();
        $('select#id_state option[country="' + country_id + '"]').show();

        if (!$('select#id_state option').is(':visible'))
            $('select#id_state option[value=""]').show();

        if(!$('select#id_state option:selected').is(':visible'))
            $('select#id_state').val($('select#id_state option:visible:first').val());
    }

    $(function () {
        $('select#id_country').on('change', countryChanged);
        countryChanged();
        $('select#id_state').val('{{ form.state.value|default_if_none:"" }}');
    });
</script>
{% endblock %}

doorsale/sales/templates/sales/checkout_base.html
{% extends catalog_template_name %}

{% block catalog-content %}
<!-- <div class="checkout-steps">
    <ul>
        <li class="{% if 'cart' in steps_processed %}processed{% endif %} {% if step_active == 'cart' %}active{% endif %}">
            <a {% if 'cart' in  steps_processed %}href="{% url 'sales_checkout_cart' %}"{% endif %}>
                <i class="fa fa-shopping-cart"></i><span>Cart</span>
            </a>
        </li>
        <li class="{% if 'billing' in steps_processed %}processed{% endif %} {% if step_active == 'billing' %}active{% endif %}">
            <a {% if 'billing' in steps_processed %}href="{% url 'sales_checkout_billing' %}"{% endif %}>
                <i class="fa fa-home"></i><span>Billing</span>
            </a>
        </li>
        <li class="{% if 'shipping' in steps_processed %}processed{% endif %} {% if step_active == 'shipping' %}active{% endif %}">
            <a {% if 'shipping' in steps_processed %}href="{% url 'sales_checkout_shipping' %}"{% endif %}>
                <i class="fa fa-truck"></i><span>Shipping</span>
            </a>
        </li>
        <li class="{% if 'payment' in steps_processed %}processed{% endif %} {% if step_active == 'payment' %}active{% endif %}">
            <a {% if 'payment' in steps_processed %}href="{% url 'sales_checkout_payment' %}"{% endif %}>
                <i class="fa fa-credit-card"></i><span>Payment</span>
            </a>
        </li>
        <li class="{% if 'order' in steps_processed %}processed{% endif %} {% if step_active == 'order' %}active{% endif %}">
            <a {% if 'order' in steps_processed %}href="{% url 'sales_checkout_order' %}"{% endif %}>
                <i class="fa fa-list"></i><span>Order</span>
            </a>
        </li>
        <li class="{% if step_active == 'receipt' %}active{% endif %}">
            <a><i class="fa fa-print"></i><span>Receipt</span></a>
        </li>
    </ul>
</div> -->
{% block checkout-content %}{% endblock %}
{% endblock %}

doorsale/sales/templates/sales/checkout_cart.html
{% extends checkout_template_name %}

{% load thumbnail %}
{% load catalog_filters %}

{% block checkout-content %}
<h3>Budgeted items</h3>
{% if error %}
<div class="error-message-box">
    {{ error }}
</div>
{% elif message %}
<div class="success-message-box">
    {{ message }}
</div>
{% endif %}
<div class="cart">
    {% with items=cart.get_items %}
    {% if items %}
    <table class="cart-items">
        <thead>
            <th>Product{{ items|pluralize }}</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub-Total</th>
        </thead>
        <tbody>
        {% for item in items %}
        {% with product=item.product %}
        <tr class="cart-item">
            <td>
                <div class="item-preview">
                    {% thumbnail product.pics.all.0.url "94x94" as im %}
                    <img src="{{ im.url }}" alt="{{ product.name }}" title="{{ product.name }}" />
                    {% endthumbnail %}
                </div>
                <a class="item-title" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            </td>
            <td>
                 <span class="price">
                     {{ product.price|currency:default_currency }}
                     {% if product.old_price %}
                     <br/>
                     <span class="old-price">{{ product.price|currency:default_currency }}</span>
                     <br/>
                     <span class="discount">{{ product.get_discount }}% OFF</span>
                     {% endif %}
                 </span>
            </td>
            <td>
                <form method="post" action="{% url 'sales_checkout_cart' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input name="quantity" type="text" class="quantity" value="{{ item.quantity }}" onchange="javascript:$(this).closest('form').submit();"/>
                    {% if product.quantity %}
                    <br/>
                    <span class="in-stock">In Stock</span>
                    {% endif %}
                </form>
            </td>
            <td>
                  <form method="post" action="{% url 'sales_remove_from_cart' %}" class="cart-item-remove">
                        {% csrf_token %}
                        <input name="product_id" type="hidden" value="{{ item.product_id }}"/>
                        <a onclick="javascript:$(this).closest('form').submit();" title="Remove this item from the cart"><i class="fa fa-trash-o"></i></a>
                    </form>
                <span class="total price">{{ item.get_sub_total|currency:default_currency }}</span>
            </td>
        </tr>
        {% endwith %}
        {% endfor %}
        </tbody>
    </table>
    <div class="cart-summary">
        <div class="cart-total">
            <table>
                <tr>
                    <td><label>Sub-Total:</label></td>
                    <td><span class="price">{{ cart.get_sub_total|currency:default_currency }}</span></td>
                </tr>
                <tr>
                    <td><label>Delivery-charge:</label></td>
                    <td><span class="price">{{ cart.get_shipping_cost|currency:default_currency }}</span></td>
                </tr>
                <tr>
                    <td><label>Tax:</label></td>
                    <td><span class="price">{{ cart.get_taxes|currency:default_currency }}</span></td>
                </tr>
                <tr>
                    <td><label>Total:</label></td>
                    <td><span class="price total">{{ cart.get_total|currency:default_currency }}</span></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="cart-options">
        <form method="post" action="{% url 'sales_remove_all_from_cart' %}" class="remove-all">
            {% csrf_token %}
            <a href="#" onclick="javascript:$(this).closest('form').submit(); return false;" title="Remove all items from the cart">Remove all from budget
            </a>
        </form>
        <a class="button" href="{% url 'catalog_index' %}" title="Go back to browse catalog"><i class="fa fa-shopping-basket" aria-hidden="true"></i>Continue browsing items</a>
        <a href="{% url 'sales_checkout_billing' %}" title="Proceed place order" class="button checkout">
            <i class="fa fa-briefcase" aria-hidden="true"></i> Contact Seller
        </a>
    </div>
    {% else %}
    <div class="no-items" >
        You have no items in your sum total calculator.
    </div>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

doorsale/sales/templates/sales/checkout_payment.html
{% extends checkout_template_name %}

{% block checkout-content %}
<form method="post" action="{% url 'sales_checkout_payment' %}" class="action-form">
	<h3>Payment Method</h3>
	{% csrf_token %}
	<ul>
		{% if error %}
		<li class="error-message-box">
			{{ error }}
		</li>
		{% endif %}
		{% for method in payment_methods %}
		<li>
			<label>
			<input name="payment_method" type="radio" value="{{ method.code }}" {% if payment_method == method.code %}checked="checked"{% endif %} />
			{{ method.name }}
			</label>
		</li>
		{% endfor %}
		<li id="id_po_number" style="display: none;">
			<h3>PO Number</h3>
			<input type="text" name="po_number" value="{{ po_number|default:'' }}" placeholder="Purchase order number..."/>
		</li>
		<li>
			<button>Next</button>
		</li>
	</ul>
</form>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
	$('input[name="payment_method"]').change(function(){
		if($(this).val() == 'PO')
			$('#id_po_number').fadeIn();
		else
			$('#id_po_number').fadeOut();
	});
	
	if($('input[name="payment_method"][value="PO"]').is(':checked'))
		$('#id_po_number').show();
</script>
{% endblock %}

doorsale/sales/templates/sales/checkout_receipt.html
{% extends checkout_template_name %}

{% block checkout-content %}
<div class="checkout-receipt">
	<h3>Order Receipt <a class="print-link button" target="_blank" href="{% url 'sales_print_receipt' order.id order.receipt_code %}">Print</a></h3>
	{% if order_confirmed %}
	<p class="success-message-box">
		Your order has been placed successfully, thank you for the order.
	</p>
	{% endif %}
	{% include "sales/parts/receipt.html" %}
</div>
{% endblock %}